export const DUMMY_EVENTS = [
  {
    id: "1",
    title: "Soirée Afterwork Le Sucre",
    description: "Rejoins-nous pour l'afterwork de la semaine au Sucre. Bonne musique, bonne ambiance !",
    category: "Soirée",
    location_name: "Le Sucre",
    location_address: "50 Quai Rambaud, Lyon 2e",
    latitude: 45.7445,
    longitude: 4.8157,
    date: "Sam. 3 Mai",
    time: "20h00",
    price: "Gratuit",
    max_participants: 100,
    participants_count: 67,
    views_count: 312,
    shares_count: 18,
    image_url: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=400&h=300&fit=crop",
    boost_active: true,
  },
  {
    id: "2",
    title: "Run Club Lyon 6e",
    description: "Sortie running du dimanche matin. Niveau intermédiaire, 10km au bord du Rhône.",
    category: "Sport",
    location_name: "Parc de la Tête d'Or",
    location_address: "Place du Général Leclerc, Lyon 6e",
    latitude: 45.7756,
    longitude: 4.8556,
    date: "Dim. 4 Mai",
    time: "09h00",
    price: "Gratuit",
    max_participants: 30,
    participants_count: 12,
    views_count: 89,
    shares_count: 5,
    image_url: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop",
    boost_active: false,
  },
  {
    id: "3",
    title: "Networking Tech & Startups",
    description: "Rencontre des entrepreneurs tech lyonnais. Pitchs, échanges et opportunités.",
    category: "Networking",
    location_name: "Station C",
    location_address: "30 Cours de la Liberté, Lyon 3e",
    latitude: 45.7568,
    longitude: 4.8432,
    date: "Mer. 7 Mai",
    time: "18h30",
    price: "10€",
    max_participants: 80,
    participants_count: 54,
    views_count: 421,
    shares_count: 32,
    image_url: "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=400&h=300&fit=crop",
    boost_active: false,
  },
  {
    id: "4",
    title: "Concert Jazz au Périscope",
    description: "Une soirée jazz live avec le quartet Louis Bernard. Ne ratez pas ça.",
    category: "Musique",
    location_name: "Le Périscope",
    location_address: "11 Rue Dalgabio, Lyon 1er",
    latitude: 45.7672,
    longitude: 4.8312,
    date: "Ven. 9 Mai",
    time: "21h00",
    price: "15€",
    max_participants: 120,
    participants_count: 98,
    views_count: 543,
    shares_count: 41,
    image_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=300&fit=crop",
    boost_active: true,
  },
  {
    id: "5",
    title: "Coworking Créatifs — Confluence",
    description: "Session coworking pour freelances et créatifs. Café inclus, venez avec vos projets.",
    category: "Travail",
    location_name: "Mama Works Confluence",
    location_address: "112 Cours Charlemagne, Lyon 2e",
    latitude: 45.7411,
    longitude: 4.8201,
    date: "Jeu. 8 Mai",
    time: "10h00",
    price: "Gratuit",
    max_participants: 40,
    participants_count: 18,
    views_count: 134,
    shares_count: 9,
    image_url: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=400&h=300&fit=crop",
    boost_active: false,
  },
  {
    id: "6",
    title: "Expo Photo Urbaine",
    description: "Vernissage de l'exposition photo de 12 artistes lyonnais. Entrée libre.",
    category: "Culture",
    location_name: "Galerie Le Bleu du Ciel",
    location_address: "42 Rue de l'Arbre Sec, Lyon 1er",
    latitude: 45.7698,
    longitude: 4.8267,
    date: "Sam. 10 Mai",
    time: "16h00",
    price: "Gratuit",
    max_participants: 60,
    participants_count: 23,
    views_count: 178,
    shares_count: 14,
    image_url: "https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?w=400&h=300&fit=crop",
    boost_active: false,
  },
];

export const DUMMY_PROMOS = [
  {
    id: "p1",
    title: "1 shot offert à l'entrée",
    description: "Présente ton compte SYNCITY vérifié et reçois 1 shot de bienvenue.",
    conditions: "Valable vendredi et samedi soir, 1 fois par personne.",
    active: true,
    redemptions: 47,
    creator_email: "partner@sucre.fr",
    establishment_id: "e1",
    created_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "p2",
    title: "-10% sur l'addition le midi",
    description: "Réduction de 10% sur tout le menu du midi.",
    conditions: "Du lundi au vendredi, de 12h à 14h. Sur présentation du QR code.",
    active: true,
    redemptions: 23,
    creator_email: "partner@ninkasi.fr",
    establishment_id: "e2",
    created_at: "2026-04-05T09:00:00Z",
  },
];

export const DUMMY_PARTNER_EVENTS = [
  {
    id: "pe1",
    title: "Soirée Inauguration",
    description: "Soirée d'inauguration de notre nouveau bar.",
    category: "Soirée",
    location_name: "Le Sucre",
    location_address: "50 Quai Rambaud, Lyon 2e",
    latitude: 45.7445,
    longitude: 4.8157,
    date: "Sam. 3 Mai",
    time: "22h00",
    price: "Gratuit",
    max_participants: 200,
    participants_count: 134,
    views_count: 892,
    shares_count: 67,
    image_url: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=400&h=300&fit=crop",
    boost_active: true,
    creator_email: "partner@example.com",
  },
  {
    id: "pe2",
    title: "DJ Set Techno",
    description: "Nuit techno avec 3 DJs locaux.",
    category: "Musique",
    location_name: "Le Sucre",
    location_address: "50 Quai Rambaud, Lyon 2e",
    latitude: 45.7445,
    longitude: 4.8157,
    date: "Sam. 17 Mai",
    time: "23h00",
    price: "10€",
    max_participants: 300,
    participants_count: 87,
    views_count: 412,
    shares_count: 29,
    image_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=300&fit=crop",
    boost_active: false,
    creator_email: "partner@example.com",
  },
];

export const DUMMY_ADMIN_ESTABLISHMENTS = [
  {
    id: "a1",
    name: "Le Sucre",
    address: "50 Quai Rambaud",
    city: "Lyon",
    owner_email: "owner@lesucre.fr",
    category: "Club",
    verification_status: "en_attente",
    verification_doc_path: "kbis_lesucre.pdf",
  },
  {
    id: "a2",
    name: "Ninkasi Opéra",
    address: "27 Rue Chavanne",
    city: "Lyon",
    owner_email: "contact@ninkasi.fr",
    category: "Bar",
    verification_status: "verifie",
    verification_doc_path: null,
  },
  {
    id: "a3",
    name: "Station C",
    address: "30 Cours de la Liberté",
    city: "Lyon",
    owner_email: "hello@stationc.fr",
    category: "Coworking",
    verification_status: "non_verifie",
    verification_doc_path: null,
  },
];

export const DUMMY_ADMIN_CONTACTS = [
  {
    id: "c1",
    name: "Marie Dupont",
    email: "marie@email.fr",
    category: "support",
    subject: "Problème de connexion",
    message: "Je n'arrive pas à me connecter à mon compte malgré le bon mot de passe.",
    created_at: "2026-04-25T14:30:00Z",
  },
  {
    id: "c2",
    name: "Antoine Martin",
    email: "antoine@startup.fr",
    category: "partenariat",
    subject: "Demande de partenariat",
    message: "Je souhaite intégrer SYNCITY dans notre espace de coworking.",
    created_at: "2026-04-26T09:15:00Z",
  },
];
